version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airlipay-dashboard
    env_file:
      - .env.local.example
    volumes:
      - /home/techarcgram/:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3001:3000"
