"use client";

import Info from "@/components/Info";
import { useSelector } from "react-redux";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function LoginLayout({ children }) {
  const { errorMessage, error } = useSelector((state) => state.account);
  return (
    <div className="grid h-screen place-items-center">
      <Info message={errorMessage} error={error} />
      {children}
    </div>
  );
}
