pipeline {
    agent any
    environment {
        CI = 'true'

    }
    stages {
        stage('Build') {
            steps {
                sh 'docker compose build'
            }
        }
        // stage('Test') {
        //     steps {
        //         sh './jenkins/scripts/test.sh'
        //     }
        // }
        stage('Deliver') {
            steps {
                sh 'docker compose up'
            }
        }
    }
}