pipeline {
    agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                // sh 'docker compose build'
                sh 'docker compose -f docker/production/docker-compose.yml build'
            }
        }

        stage('Run') {
            steps {
                // sh 'docker compose up'
                sh 'docker compose -f docker/production/docker-compose.yml up -d'
            }
        }
    }
}