name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          branches: |
            [
              'master'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

